# Site settings
email: jessica.garson@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: "Jessica Garson"
description: "DC Based Developer and Tech Inclusion Advocate."
url: ""
twitter_username: "JessicaGarson"
default_img:

# Profile settings
name: "Jessica Garson"
profile_img: https://s27.postimg.org/3oqp7fl2r/Screen_Shot_2016_12_13_at_2_51_17_PM.png
profile: "Jessica lives in Washington DC. She's the co-organizer of The Tech Lady Hackathon and Hack && Tell DC."
social:
  github: http://www.github.com/JessicaGarson
  twitter: http://www.twitter.com/JessicaGarson
  instagram: http://www.instagram.com/JessGarson

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
