# Site settings
email: jessica.garson@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: "Jessica Garson"
description: "DC Based Developer and Tech Inclusion Advocate."
url: ""
twitter_username: "JessicaGarson"
default_img:

# Profile settings
name: "Jessica Garson"
profile_img: https://s27.postimg.org/3oqp7fl2r/Screen_Shot_2016_12_13_at_2_51_17_PM.png
profile: "Jessica lives in Brooklyn, NY. 
Jessica Garson is the organizer of the Tech Lady Hackathon, and previously the organizer of Hack && Tell DC. She is a frequent teacher at DC's Hear Me Code, beginner friendly classes for women by women. She also has ran programming classes at DC area public libraries. In the fall semester of 2017, she will be teaching an advanced python class at NYU. Jessica also runs a self-published programming magazine called What's my Function. In 2015, she was named by DC FemTech as one of the most powerful Women in Tech. In 2017, one of her projects nominateher.org got named best web/mobile product of the year by technical.ly magazine. 

Previously she’s worked at ISL, Burson-Marstellar, The National Education Association, ISSI Data, and Salsa Labs. Before working in technology, Jessica worked on numerous campaigns throughout the country and got her degree in Political Science at the University of Hartford."
social:
  github: http://www.github.com/JessicaGarson
  twitter: http://www.twitter.com/JessicaGarson
  instagram: http://www.instagram.com/JessGarson

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
